# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from icp_agent.api import workload_pb2 as icp__agent_dot_api_dot_workload__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in icp_agent/api/workload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpiffeWorkloadAPIStub(object):
    """SpiffeWorkloadAPI provides methods for workloads to retrieve their SPIFFE identities
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchX509SVID = channel.unary_stream(
                '/spiffe.workload.SpiffeWorkloadAPI/FetchX509SVID',
                request_serializer=icp__agent_dot_api_dot_workload__pb2.X509SVIDRequest.SerializeToString,
                response_deserializer=icp__agent_dot_api_dot_workload__pb2.X509SVIDResponse.FromString,
                _registered_method=True)
        self.FetchX509Bundles = channel.unary_stream(
                '/spiffe.workload.SpiffeWorkloadAPI/FetchX509Bundles',
                request_serializer=icp__agent_dot_api_dot_workload__pb2.X509BundlesRequest.SerializeToString,
                response_deserializer=icp__agent_dot_api_dot_workload__pb2.X509BundlesResponse.FromString,
                _registered_method=True)
        self.ValidateJWTSVID = channel.unary_unary(
                '/spiffe.workload.SpiffeWorkloadAPI/ValidateJWTSVID',
                request_serializer=icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDRequest.SerializeToString,
                response_deserializer=icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDResponse.FromString,
                _registered_method=True)
        self.FetchJWTSVID = channel.unary_unary(
                '/spiffe.workload.SpiffeWorkloadAPI/FetchJWTSVID',
                request_serializer=icp__agent_dot_api_dot_workload__pb2.JWTSVIDRequest.SerializeToString,
                response_deserializer=icp__agent_dot_api_dot_workload__pb2.JWTSVIDResponse.FromString,
                _registered_method=True)
        self.FetchJWTBundles = channel.unary_stream(
                '/spiffe.workload.SpiffeWorkloadAPI/FetchJWTBundles',
                request_serializer=icp__agent_dot_api_dot_workload__pb2.JWTBundlesRequest.SerializeToString,
                response_deserializer=icp__agent_dot_api_dot_workload__pb2.JWTBundlesResponse.FromString,
                _registered_method=True)


class SpiffeWorkloadAPIServicer(object):
    """SpiffeWorkloadAPI provides methods for workloads to retrieve their SPIFFE identities
    """

    def FetchX509SVID(self, request, context):
        """Fetch X.509-SVID - Workloads subscribe to this RPC to receive X.509 SVIDs
        SVIDs are streamed to the workload and automatically updated before expiry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchX509Bundles(self, request, context):
        """Fetch X.509 bundles - Returns trust bundles for federated trust domains
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJWTSVID(self, request, context):
        """Validate JWT-SVID - Validates a JWT-SVID token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJWTSVID(self, request, context):
        """Fetch JWT-SVID - Fetches a JWT-SVID with specified audience
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJWTBundles(self, request, context):
        """Fetch JWT bundles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpiffeWorkloadAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchX509SVID': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchX509SVID,
                    request_deserializer=icp__agent_dot_api_dot_workload__pb2.X509SVIDRequest.FromString,
                    response_serializer=icp__agent_dot_api_dot_workload__pb2.X509SVIDResponse.SerializeToString,
            ),
            'FetchX509Bundles': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchX509Bundles,
                    request_deserializer=icp__agent_dot_api_dot_workload__pb2.X509BundlesRequest.FromString,
                    response_serializer=icp__agent_dot_api_dot_workload__pb2.X509BundlesResponse.SerializeToString,
            ),
            'ValidateJWTSVID': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJWTSVID,
                    request_deserializer=icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDRequest.FromString,
                    response_serializer=icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDResponse.SerializeToString,
            ),
            'FetchJWTSVID': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchJWTSVID,
                    request_deserializer=icp__agent_dot_api_dot_workload__pb2.JWTSVIDRequest.FromString,
                    response_serializer=icp__agent_dot_api_dot_workload__pb2.JWTSVIDResponse.SerializeToString,
            ),
            'FetchJWTBundles': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchJWTBundles,
                    request_deserializer=icp__agent_dot_api_dot_workload__pb2.JWTBundlesRequest.FromString,
                    response_serializer=icp__agent_dot_api_dot_workload__pb2.JWTBundlesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spiffe.workload.SpiffeWorkloadAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spiffe.workload.SpiffeWorkloadAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpiffeWorkloadAPI(object):
    """SpiffeWorkloadAPI provides methods for workloads to retrieve their SPIFFE identities
    """

    @staticmethod
    def FetchX509SVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spiffe.workload.SpiffeWorkloadAPI/FetchX509SVID',
            icp__agent_dot_api_dot_workload__pb2.X509SVIDRequest.SerializeToString,
            icp__agent_dot_api_dot_workload__pb2.X509SVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchX509Bundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spiffe.workload.SpiffeWorkloadAPI/FetchX509Bundles',
            icp__agent_dot_api_dot_workload__pb2.X509BundlesRequest.SerializeToString,
            icp__agent_dot_api_dot_workload__pb2.X509BundlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateJWTSVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiffe.workload.SpiffeWorkloadAPI/ValidateJWTSVID',
            icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDRequest.SerializeToString,
            icp__agent_dot_api_dot_workload__pb2.ValidateJWTSVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJWTSVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiffe.workload.SpiffeWorkloadAPI/FetchJWTSVID',
            icp__agent_dot_api_dot_workload__pb2.JWTSVIDRequest.SerializeToString,
            icp__agent_dot_api_dot_workload__pb2.JWTSVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJWTBundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spiffe.workload.SpiffeWorkloadAPI/FetchJWTBundles',
            icp__agent_dot_api_dot_workload__pb2.JWTBundlesRequest.SerializeToString,
            icp__agent_dot_api_dot_workload__pb2.JWTBundlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
